def line():
    a = float(input("Ingrese el coeficiente A: "))
    b = float(input("Ingrese el coeficiente B: "))
    x1 = float(input("Ingrese el coeficiente X1: "))
    x2 = float(input("Ingrese el coeficiente X2: "))
    print("El coeficiente A de su ecuación de la recta es: " + f"{a}")
    print("El coeficiente B de su ecuación de la recta es: " + f"{b}")
    print("El coeficiente X1 de su ecuación de la recta es: " + f"{x1}")
    print("El coeficiente X2 de su ecuación de la recta es: " + f"{x2}")
    print("\nPara la siguiente ecuación:")
    print(f"\tY = {a}X + {b}")
    print("\nDados los siguientes puntos:")
    y1 = float(a*x1 + b)
    print(f"\tP1 ({x1}, {y1})")
    y2 = float(a*x2 + b)
    print(f"\tP2 ({x2}, {y2})")
    d = (((y2-y1)**2)+((x2-x1)**2))**(1/2)
    print(f"\nLa distancia entre ellos es: {d}")
